title: "Rabies Israel Project"
author: "Dor J"
logo: "content/assets/favicon/favicon.ico"
execute:
  execute_notebooks: off
html:
  header:
    extra_css: 
      - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/flatly/bootstrap.min.css
    extra_js: 
      - https://code.jquery.com/jquery-3.5.1.slim.min.js
      - https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js
      - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js
